		
	<script>
	if(!DKI){
		var DKI = {};
	}
	DKI.strings = {
		browserWaring         : {"message":"Your current browser is obsolete. <br> For the best experience in this course (and possibly your life) we suggest one of the following browsers:","downloadIe":"Download Internet Explorer","downloadChrome":"Download Google Chrome","downloadFirefox":"Download Firefox","close":"close","downloadSafari":"Download Safari","title":"Improve your experience"},
		certificate           : {"sign":"Signature:","body":"This is to certify that <span id='certificate_studentName'><\/span> has completed the course <span id='certificate_courseName'><\/span>","print":"print","printTooltip":"Print your certificate","title":"Certificate of Completion"},
		courseSearch          : {"filterTranscripts":"Transcripts","back":"Back","filterAudio":"Audio","sequentialWarningText":"To view all search results, this course must be completed.","seeAlso":"See Also","sequentialWarningTitle":"Sequential Course","filterVideos":"Videos","foundLocations":"Found Locations","filterImages":"Images","filterTop":"Top Hits","filterText":"Text Items","filterGlossaries":"Glossary Items","filterObjectives":"Objectives","filterRichMedia":"Rich Media","inputPlaceholder":"Enter Search Term","filterReferences":"References Items","title":"Course Search"},
		doc                   : {"Drag items header":"Drag Items","Feedback table submission":"Submission","Drag table matches header":"Match(es)","Source label":"Source: ","Possible match label":"Possible Matches","Webpage element table header":"External Webpage","yes":"Yes","Element table embed code":"Embed Code","Metadata table created on":"Created On","Embedded video table header":"Embedded Video","Audio element table header":"Audio Element","Publish settings header":"Publish Settings","TOC Heading":"Contents","Publish table description":"Description","Metadata table created by":"Created By","Feedback all incorrect":"All Incorrect","Feedback incorrect attempt":"Incorrect Attempt","Settings table header":"Settings","Question feedback header":"Question Feedback","Metadata table title":"Title","Settings table pass mark":"Pass Mark","Drop targets label":"Drop Targets","True choice":"True","Element":" Element","Settings table categories":"Categories","Stream element table header":"Media Stream Element","Element table description":"Description","Link end":"[END LINK]","Metadata table header":"Properties","False choice":"False","Page transcript header":"Page Transcript","Metadata table description":"Description","transcript":"Transcript","Metadata table modified date":"Last Modified On","Correct choice label":"Correct: ","Choices header":"Choices","Glossary Heading":"Glossary","Element table URL":"URL","Feedback label":"Feedback: ","no":"No","Test answer header":"Testing Answer Key","Feedback partial attempt":"Partially Correct Attempt","student response label":"See student response","Course settings header":"Course Settings","Widget element table header":"HTML Widget Element","Targets header":"Target(s)","Page note header":"Page Note","Settings table duration":"Duration","Feedback partial":"Partially Correct","Settings table lifecycle":"Lifecycle","Publish table profile":"Publishing Profile","Page":"Page ","page of":" of ","Bibliography Heading":"Bibliography","Created date label":"Created: ","Question type label":"Question Type: ","Resources Heading":"Resources","Metadata table copy status":"Copy Status","Drag table items header":"Items","Element table title":"Title","Settings table project":"Project","Testing Heading":"Testing","Feedback all correct":"All Correct","Course metadata header":"Course Properties","Metadata table modified by":"Last Modified By","Link start":"[BEGIN LINK -","Publish table title":"Title"},
		endCourse             : {"certNotAvailable":"(Not Available)","viewCertificate":"View Certificate","testing":"Testing","testLinkLabel":"Take Test","incompleteT":"Incomplete","LearningStatusLabel":"Learning:","passingScoreLabel":"Passing Score:","testingStatusLabel":"Testing:","headerLabel":"You have reached the end of:","viewBibliography":"View Bibliography"},
		endMod                : {"testStatusLabel":"Score:","revisitContentButton":"View Content Again","reviewTestButton":"Review Test","headerText":"You have reached the end of:","learningStatusLabel":"Learning:","testingLinkLabel":"Take Test","passingScoreLabel":"Passing Score:","moduleNameLabel":"Module Name","learningLinkLabel":"Continue"},
		endTest               : {"revisitContentButton":"View Content Again","reviewLinkLabel":"Review Test","testScoreLabel":"Total score for this test:","learningStatusLabel":"Learning:","retakeTestButton":"Retake Test","moduleNameLabel":"Module Name","passingScoreLabel":"Passing Score:","testingStatusLabel":"Testing:","learningLinkLabel":"Continue","headerLabel":"You've finished the test for:"},
		glossary              : {"titleText":"Glossary","viewTermTooltip":"View this term in the browser","definitionText":"Definition"},
		goodbye               : {"message":"Thank you for exiting the content. You may now navigate away from this content."},
		index                 : {"icloseButtonLabel":"Close","outlineTabLabel":"Outline","listButtonLabel":"More","exitButtonLabel":"Exit","skipToContent":"Skip to page content.","iPageTitle":"Course Player","transcriptButtonLabel":"Transcript","previousButtonLabel":"Previous","audioButtonLabel":"Audio","resourcesButtonLabel":"Resources","menuButtonLabel":"Menu","replayButtonLabel":"Replay","skipToNavigation":"Skip to navigation.","returnToContent":"Return to page content.","feedbackTabLabel":"Feedback","glossaryButtonLabel":"Glossary","nextButtonLabel":"Next"},
		launch                : {"launchCourse":"Launch Course","pleaseWaitMessage":"Please wait while your course opens in a new window.","dontClose":"Do NOT close this window while you are taking this course or your results will not be recorded."},
		questionInstructions  : {"3":"Enter your answer","2":"Circle the correct answer(s)","1":"Circle the correct answer","6":"Match the items below","5":"Circle one answer in each list","4":"Fill in your answer for each blank"},
		references            : {"txtReferenceLink":"Access Reference","bibliographyWindowTitle":"Bibliography","viewBibliography":"View the bibliography."},
		resources             : {"txtElementLinkTitle":"Element Link","htmlType":"HTML","resourceBrowserTitle":"Resources","txtLinksHeader":"links","txtPrintableVersionTitle":"Printable version of the course","flashType":"SWF","videoType":"Videos","txtPrintableVersionHeader":"Printable Version","audioType":"Audio","imageType":"Images","txtNewWindowTitle":"Click to open in a new window","documentType":"Documents","txtSaveAs":"Right click and select \"Save as...\""},
		runtime               : {"noNavLabel":"You cannot navigate to that page yet.","media_instructions_volume":"Press plus or minus to control volume.","passText":"Pass","testingDisabled":"Testing is not enabled for this course.","autoPlayDisabler":"Touch anywhere to start your page","txtInstructionsLabel":"Please enter your feedback below.","iResume":"Please select OK to resume course, or Cancel to start over.","buttonLabelCancel":"Cancel","txtNoOutline":"No outline available","notesLabel":"Notes","exceededTestAttempts":"You have exceeded the maximum number of test attempts for this module.","media_instructions_mute":"Press 'm' to mute and un-mute audio.","txtErrorLoadCmpltn":"Error loading completion","transcriptLabel":"Transcript","mrkrErrorLabel1":"Invalid question type","txtEnterName":"Please enter your name","txtRemainingAttempts":"Remaining Attempts:","confirmQuestionNoSelection":"Are you sure you wish to submit this question without providing any answers?","txtLine1Noted":"noted:","txtTakeTest":"Take Test","txtTitleCurrentPage":"Current Page Feedback","tstchoicesLabel2":"selections.","txtNotAvailableShort":"N\/A","media_instructions_fullscreen":"Press 'f' to enter fullscreen, escape to exit fullscreen.","tstchoicesLabel1":"You cannot choose more than","resourceBrowserTitle":"Resource Browser","buttonLabelSubmit":"Submit","retakeTest":"Retake Test","txtFailedLoadAssess":"Failed to load assessment","falseOptionLabel":"False","noOutlineLabel":"No Outline Available","noModuleTesting":"This module does not have any testing.","testTryAgain":"Try Again","pretestQuestLabel":"Launch Pretest?","trueOptionLabel":"True","txtScore":"Score:","txtTitleNoFeedBack":"No Reviewer Feedback","tabLabelAllFeedBk":"All Feedback","failText":"Fail","tabLabelPageFeedBk":"Page Feedback","quitTestWarning":"You will fail this test attempt if you quit now.","media_instructions_play":"Press enter or space to play and pause the media.","buttonLabelNext":"Next","media_instructions_transcript":"Press 't' to open the transcript.","buttonLabelClose":"Close","incompleteText":"Incomplete","txtPoints":"points"}
	};
	var playerStrings = DKI.strings.runtime;
	var endscreenStrings = DKI.strings.endCourse;
	var moduleStringText = DKI.strings.endMod;
	</script>

	